name: Публикация на docker hub при успешном завершении сборки, восстановления и тестирования

on:
  push:
    branches:
      - master

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Установка dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Восстанавливаем проект
      run: dotnet restore
      
    - name: Собираем без восстановления зависимостей
      run: dotnet build -c Release --no-restore
      
    - name: Тестирование проекта
      run: dotnet test --no-restore
  build_and_pub:
    needs: [run_tests]
    runs-on: [ubuntu-latest]
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME }}
    steps:
      - name: Входим в Docker Hub
        run:  echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - uses: actions/checkout@master
      
      - name: Собираем образ из Dockerfile
        run: docker build -t $LOGIN/$NAME:${GITHUB_REF:11} -f Dockerfile .
        
      - name: Отправляем образ в Docker Hub
        run: docker push $LOGIN/$NAME:${GITHUB_REF:11}
