name: Сборка, скачивание зависимостей и тестирование проекта

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Установка dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
        
    - name: Восстанавливаем проект
      run: dotnet restore
      
    - name: Собираем без восстановления зависимостей
      run: dotnet build -c Release --no-restore
      
    - name: Тестирование проекта
      run: dotnet test --no-restore --verbosity normal
